import { expect, test } from '@playwright/test'

for (const width of [1440, 390]) {
  test(`financeiro: receita, despesa, pagamento, filtros e F5 em ${width}px`, async ({ page }) => {
    await page.setViewportSize({ width, height: 960 })
    const api = process.env.SGF_TEST_API_URL ?? 'http://localhost:5206'
    const user = { name: 'Marina Costa', companyName: 'Horizonte Comercial', email: `frontend-${crypto.randomUUID()}@example.com`, password: 'TesteFrontend123!' }
    expect((await page.request.post(api + '/api/auth/register', { data: user })).status()).toBe(201)
    await page.goto('/login')
    await page.getByLabel('E-mail', { exact: true }).fill(user.email)
    await page.getByLabel('Senha', { exact: true }).fill(user.password)
    await page.getByRole('button', { name: 'Entrar', exact: true }).click()
    await expect(page).toHaveURL(/\/app$/)
    await page.goto('/app/finance')
    await expect(page.getByRole('heading', { name: 'Nenhum lançamento financeiro' })).toBeVisible()
    const total = (name: string) => page.getByRole('article', { name, exact: true })
    await expect(total('Saldo realizado')).toContainText('R$ 0,00')
    await page.getByRole('button', { name: 'Nova receita', exact: true }).click()
    const form = page.getByRole('dialog')
    await form.getByRole('button', { name: 'Salvar lançamento' }).click()
    await expect(form).toBeVisible()
    expect(await form.locator('input[name=description]').evaluate((el: HTMLInputElement) => el.validity.valueMissing)).toBe(true)
    await form.getByLabel('Descrição', { exact: true }).fill('Serviço mensal')
    await form.getByLabel('Categoria', { exact: false }).fill('Serviços')
    await form.getByLabel('Valor (R$)', { exact: true }).fill('0')
    await form.getByLabel('Vencimento', { exact: true }).fill('2026-09-20')
    await form.getByRole('button', { name: 'Salvar lançamento' }).click()
    expect(await form.locator('input[name=amount]').evaluate((el: HTMLInputElement) => el.validity.rangeUnderflow)).toBe(true)
    await form.getByLabel('Valor (R$)', { exact: true }).fill('1000')
    await form.getByLabel('Observação', { exact: false }).fill('Recebimento manual')
    await page.screenshot({ path: `test-results/finance-form-${width}.png`, fullPage: true })
    const posted = page.waitForRequest(r => r.method() === 'POST' && r.url().endsWith('/api/finance'))
    await form.getByRole('button', { name: 'Salvar lançamento' }).click()
    expect(Object.keys((await posted).postDataJSON()).sort()).toEqual(['amount', 'category', 'description', 'dueDate', 'notes', 'type'])
    await expect(form).not.toBeVisible()
    await expect(total('A receber')).toContainText('R$ 1.000,00')
    await expect(total('Saldo realizado')).toContainText('R$ 0,00')

    await page.getByRole('button', { name: 'Nova despesa', exact: true }).click()
    await form.getByLabel('Descrição', { exact: true }).fill('Aluguel')
    await form.getByLabel('Categoria', { exact: false }).fill('Estrutura')
    await form.getByLabel('Valor (R$)', { exact: true }).fill('250')
    await form.getByLabel('Vencimento', { exact: true }).fill('2026-09-21')
    await form.getByRole('button', { name: 'Salvar lançamento' }).click()
    await expect(total('A pagar')).toContainText('R$ 250,00')
    await page.getByRole('button', { name: 'Editar Aluguel', exact: true }).click()
    await expect(form.getByRole('combobox', { name: 'Tipo', exact: true })).toBeDisabled()
    await form.getByLabel('Valor (R$)', { exact: true }).fill('300')
    await form.getByRole('button', { name: 'Salvar lançamento' }).click()
    await expect(total('A pagar')).toContainText('R$ 300,00')
    await expect(page.locator('.finance-table tbody tr')).toHaveCount(2)
    await page.screenshot({ path: `test-results/finance-pending-${width}.png`, fullPage: true })

    page.on('dialog', dialog => dialog.accept())
    await page.getByRole('button', { name: 'Receber Serviço mensal', exact: true }).click()
    await expect(total('Recebido')).toContainText('R$ 1.000,00')
    await page.getByRole('button', { name: 'Pagar Aluguel', exact: true }).click()
    await expect(total('Pago')).toContainText('R$ 300,00')
    await expect(total('Saldo realizado')).toContainText('R$ 700,00')
    await expect(total('A receber')).toContainText('R$ 0,00')
    await expect(total('A pagar')).toContainText('R$ 0,00')
    await expect(page.getByRole('button', { name: 'Editar Aluguel', exact: true })).toHaveCount(0)
    await page.getByRole('button', { name: 'Ver detalhes de Aluguel', exact: true }).click()
    await expect(form.getByLabel('Valor (R$)', { exact: true })).toBeDisabled()
    await expect(form.getByRole('button', { name: 'Salvar lançamento' })).toHaveCount(0)
    await form.getByRole('button', { name: 'Fechar', exact: true }).click()

    const filters = page.getByRole('form', { name: 'Filtrar lançamentos' })
    await filters.getByLabel('Buscar descrição').fill('SERVIÇO')
    await filters.getByRole('combobox', { name: 'Tipo', exact: true }).selectOption('Income')
    await filters.getByRole('combobox', { name: 'Status', exact: true }).selectOption('Paid')
    await filters.getByLabel('Categoria', { exact: true }).fill('serviços')
    await filters.getByLabel('Vencimento de', { exact: true }).fill('2026-09-20')
    await filters.getByLabel('Até', { exact: true }).fill('2026-09-20')
    await filters.getByRole('button', { name: 'Filtrar', exact: true }).click()
    await expect(page.locator('.finance-table tbody tr')).toHaveCount(1)
    await expect(page.locator('.finance-table tbody')).toContainText('Serviço mensal')
    // Totals are company-wide and independent of table filters.
    await expect(total('Saldo realizado')).toContainText('R$ 700,00')
    await page.reload()
    await expect(page.locator('.finance-table tbody tr')).toHaveCount(1)
    await expect(total('Saldo realizado')).toContainText('R$ 700,00')
    await filters.getByRole('button', { name: 'Limpar', exact: true }).click()
    await expect(page.locator('.finance-table tbody tr')).toHaveCount(2)
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
    await page.screenshot({ path: `test-results/finance-${width}.png`, fullPage: true })
    if (width === 1440) {
      for (const size of [1024, 768]) {
        await page.setViewportSize({ width: size, height: 960 })
        expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
        await page.screenshot({ path: `test-results/finance-${size}.png`, fullPage: true })
      }
    }
  })
}
