import { expect, test } from '@playwright/test'

for (const width of [1440, 390]) {
  test(`estoque completo, historico e F5 em ${width}px`, async ({ page }) => {
    await page.setViewportSize({ width, height: 900 })
    const api = process.env.SGF_TEST_API_URL ?? 'http://localhost:5206'
    const user = { name: 'Marina Costa', companyName: 'Horizonte Comercial', email: `frontend-${crypto.randomUUID()}@example.com`, password: 'TesteFrontend123!' }
    expect((await page.request.post(api + '/api/auth/register', { data: user })).status()).toBe(201)
    await page.goto('/login')
    await page.getByLabel('E-mail', { exact: true }).fill(user.email)
    await page.getByLabel('Senha', { exact: true }).fill(user.password)
    await page.getByRole('button', { name: 'Entrar', exact: true }).click()
    await expect(page).toHaveURL(/\/app$/)
    await page.goto('/app/products')
    await page.getByRole('button', { name: 'Novo produto', exact: true }).first().click()
    await page.getByLabel('Nome', { exact: true }).fill('Mouse sem fio')
    await page.getByLabel('SKU', { exact: true }).fill('MOU-001')
    await page.getByLabel('Estoque mínimo', { exact: true }).fill('8')
    await expect(page.getByLabel('Saldo atual', { exact: true })).toHaveCount(0)
    await page.getByRole('button', { name: 'Salvar produto' }).click()
    await expect(page.getByRole('status')).toContainText('Produto cadastrado')

    await page.goto('/app/inventory?view=movements')
    await expect(page.getByRole('heading', { name: 'Nenhuma movimentação registrada.' })).toBeVisible()
    await page.getByRole('navigation', { name: 'Seções de estoque' }).getByRole('link', { name: 'Estoque', exact: true }).click()
    const row = page.getByRole('row').filter({ hasText: 'MOU-001' })
    await expect(row.locator('.stock-current')).toHaveText('0')
    await expect(row.getByText('Estoque baixo', { exact: true })).toBeVisible()
    await page.getByRole('button', { name: 'Entrada de Mouse sem fio', exact: true }).click()
    await expect(page.getByRole('dialog')).toContainText('Saldo atual: 0')
    await page.getByLabel('Quantidade', { exact: true }).fill('10')
    await page.getByLabel('Observação').fill('Recebimento inicial')
    await page.screenshot({ path: `test-results/inventory-entry-${width}.png`, fullPage: true })
    const posted = page.waitForRequest(r => r.method() === 'POST' && r.url().endsWith('/api/inventory/entries'))
    await page.getByRole('button', { name: 'Registrar entrada', exact: true }).click()
    expect(Object.keys((await posted).postDataJSON()).sort()).toEqual(['notes', 'productId', 'quantity'])
    await expect(page.getByRole('status')).toContainText('Entrada registrada. Saldo atual: 10')
    await expect(row.locator('.stock-current')).toHaveText('10')
    await expect(row.getByText('Normal', { exact: true })).toBeVisible()

    await page.getByRole('button', { name: 'Saída de Mouse sem fio', exact: true }).click()
    await page.getByLabel('Quantidade', { exact: true }).fill('3')
    await page.getByLabel('Observação').fill('Saída manual')
    await page.getByRole('button', { name: 'Registrar saída', exact: true }).click()
    await expect(row.locator('.stock-current')).toHaveText('7')
    await expect(row.getByText('Estoque baixo', { exact: true })).toBeVisible()
    await page.getByRole('button', { name: 'Saída de Mouse sem fio', exact: true }).click()
    await page.getByLabel('Quantidade', { exact: true }).fill('8')
    await expect(page.getByRole('alert')).toHaveText('Estoque insuficiente para esta saída.')
    await expect(page.getByRole('button', { name: 'Registrar saída', exact: true })).toBeDisabled()
    await page.getByRole('button', { name: 'Cancelar', exact: true }).click()
    await page.getByLabel('Somente estoque baixo').click()
    await expect(page.getByLabel('Somente estoque baixo')).toBeChecked()
    await expect(row).toBeVisible()
    await page.reload()
    await expect(row.locator('.stock-current')).toHaveText('7')
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
    await page.screenshot({ path: `test-results/inventory-${width}.png`, fullPage: true })

    await page.getByRole('link', { name: 'Histórico de Mouse sem fio', exact: true }).click()
    const historyRows = page.locator('.movement-table tbody tr')
    await expect(historyRows).toHaveCount(2)
    await expect(historyRows.first()).toContainText('Saída')
    await expect(historyRows.first().locator('[data-label="Quantidade"]')).toHaveText('3')
    await expect(historyRows.last()).toContainText('Entrada')
    await expect(historyRows.last().locator('[data-label="Quantidade"]')).toHaveText('10')
    await expect(historyRows.last()).toContainText('Recebimento inicial')
    await expect(historyRows.first()).toContainText('Marina Costa')
    await page.reload()
    await expect(historyRows).toHaveCount(2)
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
    await page.screenshot({ path: `test-results/inventory-history-${width}.png`, fullPage: true })
    await page.getByRole('combobox', { name: 'Tipo', exact: true }).selectOption('Entry')
    await expect(historyRows).toHaveCount(1)
    await expect(historyRows.first()).toContainText('Entrada')
    // Another request consumes stock after this form has read its balance.
    await page.getByRole('navigation', { name: 'Seções de estoque' }).getByRole('link', { name: 'Estoque', exact: true }).click()
    await page.getByRole('button', { name: 'Saída de Mouse sem fio', exact: true }).click()
    await expect(page.getByRole('dialog')).toContainText('Saldo atual: 7')
    await page.getByLabel('Quantidade', { exact: true }).fill('3')
    await page.evaluate(async () => {
      const modulePath = '/src/features/auth/session.ts'
      const session = await import(modulePath)
      const stock = await session.authenticatedRequest('/api/inventory')
      await session.authenticatedRequest('/api/inventory/exits', {
        method: 'POST', body: JSON.stringify({ productId: stock.items[0].productId, quantity: 6 }),
      })
    })
    const rejected = page.waitForResponse(r => r.request().method() === 'POST' && r.url().endsWith('/api/inventory/exits'))
    await page.getByRole('button', { name: 'Registrar saída', exact: true }).click()
    const response = await rejected
    expect(response.status()).toBe(409)
    expect((await response.json()).code).toBe('insufficient_stock')
    await expect(page.getByRole('dialog')).toContainText('Estoque insuficiente para esta saída.')
    await expect(page.getByRole('dialog')).toContainText('Saldo atual: 1')
  })
}
