import { expect, test } from '@playwright/test'

for (const width of [1440, 390]) {
  test(`produtos: ciclo completo em ${width}px`, async ({ page }) => {
    await page.setViewportSize({ width, height: 900 })
    const api = process.env.SGF_TEST_API_URL ?? 'http://localhost:5206'
    const account = { name: 'Marina Costa', companyName: 'Horizonte Comercial', email: `frontend-${crypto.randomUUID()}@example.com`, password: 'TesteFrontend123!' }
    expect((await page.request.post(api + '/api/auth/register', { data: account })).status()).toBe(201)
    await page.goto('/login')
    await page.getByLabel('E-mail', { exact: true }).fill(account.email)
    await page.getByLabel('Senha', { exact: true }).fill(account.password)
    await page.getByRole('button', { name: 'Entrar', exact: true }).click()
    await expect(page).toHaveURL(/\/app$/)
    await page.goto('/app/products')
    await expect(page.getByRole('heading', { name: 'Nenhum produto cadastrado' })).toBeVisible()
    await page.getByRole('button', { name: 'Novo produto', exact: true }).first().click()
    const form = page.getByRole('dialog', { name: 'Novo produto' })
    await page.getByRole('button', { name: 'Salvar produto' }).click()
    expect(await form.locator('form').evaluate(el => (el as HTMLFormElement).checkValidity())).toBe(false)
    await page.getByLabel('Nome', { exact: true }).fill('Mouse sem fio')
    await page.getByLabel('SKU', { exact: true }).fill('mou-001')
    await page.getByLabel('Descrição').fill('Mouse ergonômico')
    await page.getByLabel('Preço de custo').fill('45')
    await page.getByLabel('Preço de venda').fill('-1')
    await page.getByRole('button', { name: 'Salvar produto' }).click()
    expect(await form.locator('form').evaluate(el => (el as HTMLFormElement).checkValidity())).toBe(false)
    await page.getByLabel('Preço de venda').fill('79.90')
    await page.screenshot({ path: `test-results/product-form-${width}.png`, fullPage: true })
    const creation = page.waitForRequest(r => r.method() === 'POST' && r.url().endsWith('/api/products'))
    await page.getByRole('button', { name: 'Salvar produto' }).click()
    const body = (await creation).postDataJSON()
    expect(Object.keys(body).sort()).toEqual(['costPrice', 'description', 'minimumStock', 'name', 'salePrice', 'sku'])
    expect(typeof body.salePrice).toBe('number')
    await expect(form).not.toBeVisible()
    await expect(page.getByRole('status')).toContainText('Produto cadastrado')
    await expect(page.getByText('Mouse sem fio', { exact: true })).toBeVisible()
    await expect(page.getByText('MOU-001', { exact: true })).toBeVisible()
    await expect(page.getByText(/R\$\s*79,90/)).toBeVisible()

    await page.getByRole('button', { name: 'Novo produto', exact: true }).click()
    await page.getByLabel('Nome', { exact: true }).fill('Outro mouse')
    await page.getByLabel('SKU', { exact: true }).fill('MOU - 001')
    await page.getByRole('button', { name: 'Salvar produto' }).click()
    await expect(page.getByRole('alert')).toContainText('Este SKU já está cadastrado')
    await page.getByRole('button', { name: 'Cancelar', exact: true }).click()

    await page.getByRole('button', { name: 'Editar Mouse sem fio', exact: true }).click()
    await expect(page.getByLabel('Descrição')).toHaveValue('Mouse ergonômico')
    await page.getByLabel('Nome', { exact: true }).fill('Mouse ergonômico')
    await page.getByLabel('Preço de venda').fill('39.90')
    await page.getByRole('button', { name: 'Salvar produto' }).click()
    await expect(page.getByRole('status')).toContainText('Produto atualizado')
    await expect(page.getByText('Mouse ergonômico', { exact: true })).toBeVisible()

    await page.getByLabel('Buscar por nome ou SKU').fill('inexistente')
    await page.getByRole('button', { name: 'Buscar produtos' }).click()
    await expect(page.getByRole('heading', { name: 'Nenhum produto encontrado' })).toBeVisible()
    await page.getByLabel('Buscar por nome ou SKU').fill('mou')
    await page.getByRole('button', { name: 'Buscar produtos' }).click()
    await expect(page.getByText('Mouse ergonômico', { exact: true })).toBeVisible()
    await page.reload()
    await expect(page.getByText('Mouse ergonômico', { exact: true })).toBeVisible()
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
    await page.screenshot({ path: `test-results/products-${width}.png`, fullPage: true })
    page.once('dialog', dialog => dialog.accept())
    await page.getByRole('button', { name: 'Desativar Mouse ergonômico', exact: true }).click()
    await expect(page.getByText('Inativo', { exact: true })).toBeVisible()
    await expect(page.getByRole('status')).toContainText('Produto desativado')
    await page.getByRole('combobox', { name: 'Status', exact: true }).selectOption('true')
    await expect(page.getByRole('heading', { name: 'Nenhum produto encontrado' })).toBeVisible()
    await page.getByRole('combobox', { name: 'Status', exact: true }).selectOption('false')
    await page.getByRole('button', { name: 'Reativar Mouse ergonômico', exact: true }).click()
    await expect(page.getByRole('status')).toContainText('Produto reativado')
  })
}
